spring.datasource.url: jdbc:mysql://localhost:3306/productarticles?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
server.port: 8080